### ISSUE TITLE
completely broken on powercord after latest changes

### ISSUE THREAD

**Issue by hexa0** [snappercord/dark-discord#11]
i managed to fix it by manually reverting to 310b3d982171b3fba002a3b1ac4f1778fb78362f with

`git checkout 310b3d982171b3fba002a3b1ac4f1778fb78362f`

didn't do any further testing to check which commit caused it as i just wanted the theme to work until it gets fixed

**Comment by cgytrus** [comment]
it looks like the author moved some files around through the github website, didn't test and forgot to update index.scss to point to the new relative location of source.scss (which is now just `./source` instead of `./src/source`)

**Comment by marioparaschiv** [comment]
My bad, should be fine now.
