### ISSUE TITLE
Every reboot of discord, the theme is applied but i have to untoggle and retoggle for it to work.

### ISSUE THREAD

**Issue by Kuharri** [snappercord/dark-discord#4]
i have no idea how to use github, like i said in title

**Comment by Snapperito** [comment]
assuming you're using bd, download the updated darkdiscord from [here](https://snapper.dev/download/?darkdiscord)

**Comment by Kuharri** [comment]
using powercord

**Comment by Snapperito** [comment]
go into your Dark Discord directory and git pull.

**Comment by Kuharri** [comment]
example
every start its normal and i have to go and toggle it.
i've been experiencing some issues with slook theme. so possibly could be
that.

**Comment by Kuharri** [comment]
i linked a gif but not sure if it sent, (sent through email)

**Comment by Snapperito** [comment]
yeah, the gif didnt send. you can send it via the github website, or on discord (snapper#0001)
